### ISSUE TITLE
Can we migrate Oracle to mongodb using mongify utility.

### ISSUE THREAD

**Issue by sspr28** [anlek/mongify-mongoid#5]
I am getitng the below errors

D:\Public\ruby>mongify check database.config
D:/Public/ruby/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': Could not load 'active_record/connection_adapters/Oracle_adapte
r'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem t
o the Gemfile. (LoadError)
        from D:/Public/ruby/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from D:/Public/ruby/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
        from D:/Public/ruby/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
        from D:/Public/ruby/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
        from D:/Public/ruby/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/connection_specification.rb:174:in `spec'
        from D:/Public/ruby/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_handling.rb:53:in `establish_connection'
        from D:/Public/ruby/lib/ruby/gems/2.3.0/gems/mongify-1.3.0/lib/mongify/database/sql_connection.rb:40:in `setup_connection_adapter'
        from D:/Public/ruby/lib/ruby/gems/2.3.0/gems/mongify-1.3.0/lib/mongify/database/sql_connection.rb:56:in `has_connection?'
        from D:/Public//ruby/lib/ruby/gems/2.3.0/gems/mongify-1.3.0/lib/mongify/cli/command/worker.rb:95:in `check_sql_connection'
        from D:/Public/ruby/lib/ruby/gems/2.3.0/gems/mongify-1.3.0/lib/mongify/cli/command/worker.rb:64:in `execute'
        from D:/Public/ruby/lib/ruby/gems/2.3.0/gems/mongify-1.3.0/lib/mongify/cli/application.rb:28:in `execute!'
        from D:/Public/ruby/lib/ruby/gems/2.3.0/gems/mongify-1.3.0/bin/mongify:15:in `<top (required)>'
        from D:/Public/z015360/ruby/bin/mongify:22:in `load'
        from D:/Public/z015360/ruby/bin/mongify:22:in `<main>'.

I tried to install the adapters ..

Please help to fix the issue if any one successfully migrated from oracle to mongo using mongify.

Thanks,
Prabhu

**Comment by willyd61** [comment]
How did  you try and install the adapter? That adapter name doesn't look valid, have a look at 
https://github.com/rsim/oracle-enhanced

That is what I use to access Oracle. Make sure the mongify gemfile has the adapter enabled, and you can always verify against gemlist.
